--- 
abstract: "a blosxom helper module and source filter to provide a "
author: Gavin Carr <gavin@openfusion.com.au>, http://www.openfusion.net/
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Blosxom-Debug
no_index: 
  directory: 
    - inc
    - t
requires: 
  Filter::Simple: 0
version: 0.001
